name = "onepixel"
main = "worker.js"
compatibility_date = "2024-09-23"

[assets]
directory = "."
binding = "ASSETS"
not_found_handling = "404-page"

[vars]
ADMOB_PUBLISHER_ID = "pub-4835070281978073"

[[kv_namespaces]]
binding = "SUGGESTIONS"
id = "aef5247955a449b2b2e8997ce47e78ee"
